<div class="main-container">
    <div class="banner-content">
        <img class="banner" src="http://www.cantinhodasessencias.com.br/loja/pub/media/wysiwyg/banner.png" alt="">
    </div>
    <?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="container-inner">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Categorytop\Block\Categorytop')->setTemplate('Plazathemes_Categorytop::categorytop.phtml')->toHtml();?>
	</div>
	<div class="category-home">
		<div class="container-inner">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_categor1_home')->toHtml();?>	
		</div>
	</div>
	<div class="static1">
		<div class="container-inner">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static1_home1')->toHtml();?>
		</div>
	</div>
	<div class="gruod-pruduct">
		<div class="container-inner">
			<div class="row">
				<div class="col-sm-4">
                    <?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>					
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Recentproductslider\Block\Products')->setTemplate('Plazathemes_Recentproductslider::productslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('Plazathemes_Bestsellerproduct::bestsellerproduct.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
    <div>
		<div class="testimonial-bg">
			<div class="container-inner">
				<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('Plazathemes_Testimonial::testimonial.phtml')->toHtml();?>
			</div>
		</div>
		<div class="container-inner">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
		</div>
	</div>
</div>
<div class="footer-newsletter">
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?>
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_follow')->toHtml();?>
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static1_footer')->toHtml();?>
	</div>
</div>
