<div class="footer-container">
	
	<?php //echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	<div class="footer-newsletter">
		<div class="container-inner">
			<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?>
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_follow')->toHtml();?>
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static1_footer')->toHtml();?>
		</div>
	</div>
	<div class="footer-top">
		<div class="container-inner">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top')->toHtml();?>
		</div>
	</div>
	<div class="footer-bottom" style="background-color: #cc353a; padding-top: 30px">
		<div class="container-inner">
			<div class="row">
				<div class="col-md-4">
				<img src="http://127.0.0.1/cantinho/pub/media/logo/stores/1/cantinho.png" alt="Cantinho das Essências" width="366" height="94">
				</div>
				<div class="col-md-5">
					<p style="font-size: 14px; color: #fff;">R. Dr. Álvaro Soares, 380 (45,39 km) | 18010-191 Sorocaba</p>		
					<h3 style="font-size: 24px; color: #fff;">15 3388-6756 / 3233-8723</h3>
				</div>
				<div class="col-md-3">
					<div class="footer_payment">
					<img src="http://127.0.0.1/cantinho/pub/media/logo/stores/1/logos-footer.png" alt="Cantinho das Essências" style="max-width: 100%; height: auto; display: block">
					</div>	
				</div>
			</div>
		</div>
		<div id="back_top">
			<a href="#back-top"><span>>top</span></a>
		</div>
	</div>
</div>
<script type="text/javascript">
			
	require(["jquery"], function($){

	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});
		   $('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		}); 
	   
	});
</script>