	<?php //echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
  <div id="infoentrega" class="posiciona" style="display: none">
  <div id="fechar" align=right><a href="javascript:off(1);">FECHAR</a></div>
  Envio e Entrega

1. Separação do pedido
Após o fechamento do pedido e confirmação do pagamento, o Cantinho das Essências terá até 2
(dois) dias úteis para a liberação da mercadoria para ser enviada, ou retirada pelo cliente em nossa
loja física.
2. Disponibilidade dos produtos
Os produtos selecionados e colocados no carrinho de compras pelo cliente durante a
navegação na loja virtual do Cantinho das Essências somente serão reservados após a
conclusão do pedido (constatação do pagamento).  Se no ato da conclusão do pedido a
mercadoria não estiver mais disponível, o cliente será avisado. E em caso de
impossibilidade de comunicação com o cliente, o Cantinho das Essências poderá
efetuar o envio imediato das demais mercadorias que constam na loja virtual, sendo
restituído ao cliente o devido valor da (s) mercadoria (s) faltante (s).
3. Valores e prazos de envio:
Normalmente a entrega dos pedidos pelo Cantinho Das Essências aos seus clientes é feita pelos
Correios. O valor do frete e prazo de entrega será calculado no momento de fechamento do pedido,
de acordo com a tabela e as regras de cobrança utilizadas pelos Correios.
4. Rastreamento do pedido:
Os pedidos possuirão um código de rastreio, que será enviado via e-mail ao cliente assim que a
mercadoria for postada. Com esse número é possível acompanhar a entrega do pedido através da
página dos correios:
https://www2.correios.com.br/sistemas/rastreamento/default.cfm
5. Opções de envio:
Dependendo do volume do pedido e do local de entrega indicado pelo cliente, ou se ainda o cliente
assim preferir, a entrega poderá ser feita através de transportadora ou motoboy. O valor do envio
será cotado previamente e informado ao cliente antes do envio da mercadoria.
6. Entrega
Correio: os agentes dos Correios realizam até 03 (três) tentativas de entrega no endereço informado,
sendo assim, é indispensável que permaneça alguém no local indicado para receber o produto e
assinar o comprovante de entrega. Caso as 03 (três) tentativas não tenham sucesso, o pedido será
encaminhado a um centro de distribuição dos Correios, e se mesmo assim não for coletado pelo
cliente, retornará para o Cantinho das Essências.
O reenvio do produto somente será possível mediante a confirmação de endereço. O prazo para
reenvio será o mesmo informado no processo de compra.
No caso de reentrega, o cliente deverá fazer o pagamento antecipado da nova taxa de entrega.
Transportadora: a transportadora realiza somente 01 (uma) tentativa de entrega no local informado,
sendo assim, é indispensável que permaneça alguém no endereço indicado para receber o produto e
assinar o comprovante de entrega. Caso a tentativa não tenha sucesso pelo fato de ninguém estar no
local de entrega para receber a mercadoria, ela volta para a filial da transportadora, e será entregue
somente depois do contato com o cliente. Se a transportadora cobrar a reentrega, o valor será de
responsabilidade do cliente.

7. Atrasos na entrega:
O Cantinho das Essências se disponibiliza a ajudar o cliente em casos atraso, erros de endereço e
outros problemas ocasionais.
Nesses casos, entre em contato para maiores informações e melhor condução da situação através de
nossos canais de atendimento.
Empresas responsáveis pela entrega: a partir do momento em que houve a postagem e o envio do
número do rastreamento ou frete, atrasos na entrega são de inteira responsabilidade do sistema de
entrega dos Correios ou da transportadora que presta o serviço terceirizado.
8. Recusa da entrega:
Entrega do produto deve ser recusada sempre que se constatar as seguintes situações:
 Embalagem aberta ou avariada;
 Produto avariado;
 Produto em desacordo com o pedido;
 Falta de envio de produto ou acessórios.
No caso de recusa no recebimento do pedido, favor entrar em contato com o Cantinho das Essências,
através de nossos canais de atendimento, para podermos proceder com a solução do problema.

Em caso de dúvidas, entre em contato através de um dos canais de comunicação da &#39;Central de
Atendimento&#39;:
E-mail: contato@cantinhodasessencias.com.br;
Telefone: (15) 3233-8723 ou (15) 3388-6756;
WhatsApp: (15) 99126-8435.
Horário de atendimento: de segunda a sexta das 9h às 18h e aos sábados das 9h às 13h.
  </div>
  <div id="termoscondicoes" class="posiciona" style="display: none">
  <div id="fechar" align=right><a href="javascript:off(3);">FECHAR</a></div>
  Política de Troca e Devolução

  O Cantinho das Essências prioriza o cliente em todas as suas ações, assegurando uma ótima experiência de
  compra, desde a navegação no site até o recebimento do produto. Para garantir a satisfação e manter uma
  relação transparente e confiável, criamos a nossa política de troca e devolução, tendo como base o Código
  de Defesa do Consumidor.
  1) Regras
  O cliente tem o direito de se arrepender da compra ou solicitar a trocar do produto no prazo máximo de 7
  (sete) dias após o recebimento da mercadoria, como consta no Decreto nº 7.962/2013 do direito do
  consumidor.
  2) Contato
  Para qualquer solicitação de troca ou devolução de mercadorias, entre em contato com o Cantinho das
  Essências no e-mail contato@cantinhodasessencias.com.br, informando o motivo da troca ou devolução.

  3) Produto com defeito
  Em caso de produto com defeito o consumidor terá o prazo de até 30 dias a contar da data do
  recebimento do produto para requerer a troca diretamente pelo Cantinho das Essências.
  Os produtos devolvidos serão analisados em até 5 (cinco) dias úteis, após a data do recebimento na loja.
  Uma vez constado defeito de fabricação, o cliente terá as seguintes opções:
  • Receber um novo produto, igual ao adquirido anteriormente (havendo disponibilidade no estoque);
  • Ressarcimento do valor do produto, na mesma forma que foi pago;
  • Vale compras no mesmo valor do produto devolvido, para utilizar em compras futuras.
  Em caso de produtos já manipulados apresentando algum desvio de qualidade faremos a devolução
  após envio de amostra (mínimo de 100ml) para análise técnica. Se, após avaliação, realmente for
  constatado alguma alteração em questão de qualidade, faremos a troca por matérias-primas novas ou
  o valor da mercadoria avariada.
  Será procedimento padrão a análise das solicitações troca pelo Cantinho das Essências. Se não for
  constatado qualquer defeito ou se for descumprida qualquer das condições descritas, o produto será
  reenviado ao cliente.

  4) Produto com avaria
  Todos os produtos transportados são cuidadosamente embalados, visando garantir segurança durante o
  transporte. No entanto, caso haja qualquer tipo de avaria e/ou danos à embalagem ou aos produtos, recuse o
  recebimento e informe o ocorrido através do e-mail contato@cantinhodasessencias.com.br.
  Orientamos que você confira sempre sua mercadoria no ato da entrega realizada pelos Correios ou
  transportadora. Recuse o recebimento caso ocorra alguma das hipóteses abaixo:
   Embalagem aberta ou avariada;
   Produto avariado;
   Produto em desacordo com o pedido;
   Falta de envio de produto ou acessórios.

  Caso tenha notado danos somente após o recebimento do produto, nos envie fotos, vídeos e uma descrição
  detalhada do problema apresentado, para que possa ser analisado pela equipe do Cantinho das Essências.
  A mercadoria recebida, caso em desacordo com a expectativa, não poderá ser descartada ou mesmo
  manipulada, ficando a critério do Cantinho das Essências o procedimento de devolução a ser realizado.

  5) Arrependimento
  Em caso de arrependimento, o produto deve ser encaminhado (dentro do prazo mencionado acima) em
  embalagem original, sem indícios de uso e sem violação da embalagem ou lacre.
  Caso o cliente se arrependa da compra, têm as seguintes opções de ressarcimento:
  • Ressarcimento do valor do produto devolvido, na mesma forma que foi pago;
  • Vale compras no mesmo valor do produto, para utilizar em compras futuras.
  6) Envio
  Após o recebimento do produto devolvido pelo cliente em nossa empresa, o prazo de troca e envio
  do produto substituto é de até 20 (vinte) dias úteis. Se o produto constar em estoque na empresa, o
  prazo será de 5 (cinco) dias úteis.
  A forma de envio para devolução de produtos é determinada pelo Cantinho das Essências, por isso, é
  indispensável o contato com a nossa equipe no e-mail contato@cantinhodasessencias.com.br.
  Orientaremos o passo a passo do processo para troca e/ou devolução.
  Guarde sempre o Cupom ou Nota Fiscal e a embalagem original do produto, pois eles serão

  indispensáveis em casos de troca ou devolução.

  O pedido de desistência passará por uma avaliação, para verificar se houve o atendimento dos requisitos
  acima e se tal (ais) produto (s) não foi (oram) utilizado (s) ou danificado (s), mesmo que parcialmente. Caso
  alguma destas situações tenha ocorrido, a devolução não será aceita.
  </div>
  <div id="perguntasfrequentes" class="posiciona" style="display: none">
  <div id="fechar" align=right><a href="javascript:off(4);">FECHAR</a></div>
  Perguntas frequentes

   Cancelamento da compra
  Como faço para cancelar minha compra?
  1) Se a forma de pagamento escolhida foi o boleto bancário e o pagamento ainda não foi efetuado, o
  pedido será cancelado automaticamente no dia seguinte ao vencimento do boleto, sem ônus para
  você.
  2) Caso tenha efetuado o pagamento com cartão de crédito e a Nota Fiscal não tiver sido emitida,
  você poderá solicitar o cancelamento entrando em contato com nossa Central de Atendimento e
  nos envie um e-mail.

   Formas de pagamento
  Cartão de Crédito
  Toda aprovação ou reprovação do crédito é feito através da operadora REDE e o cartão emissor do cliente.
  Boleto Bancário
  Para sua maior comodidade todas as suas compras podem ser pagas através de boleto bancário, à vista.
  Importante:
  1- Aguarde o e-mail de confirmação do seu pedido para efetuar o pagamento do boleto bancário.
  3- Lembramos que a liberação para entrega do seu pedido somente acontecerá após a confirmação do
  respectivo pagamento do boleto bancário pelo banco, o que geralmente ocorre 2 (dois) dias úteis após a
  quitação.
  Depósito ou Transferência Bancária
  Suas compras poderão ser pagas através de depósito bancário ou transferência bancária.
  O pedido será liberado para separação e envio, após o valor ter sido creditado na conta da empresa.
  É necessário enviar o comprovante de depósito ou transferência através do email:
  contato@cantinhodasessencias.com.br
  Dados para depósito:
  Banco Itaú
  Agência: 0076
  Conta Corrente: 20100-3
  CNPJ: 04.692.843/0001-57
  </div>
  <div id="segurancaprivacidade" class="posiciona" style="display: none">
  <div id="fechar" align=right><a href="javascript:off(2);">FECHAR</a></div>
  Segurança e privacidade

  O Cantinho das Essências tem o compromisso com a privacidade e a segurança dos nossos clientes durante
  todo o processo de navegação e compra pelo site. Os dados cadastrais não são vendidos, trocados ou
  divulgados para terceiros, exceto quando essas informações são necessárias para o processo de entrega, para
  cobrança ou para a participação em promoções solicitadas pelos clientes.
  Os seus dados pessoais serão fundamentais para que o pedido seja entregue em segurança, de acordo com os
  prazos de entrega. A qualquer momento, o cliente poderá modificar essas informações ou solicitar a
  exclusão. Oferecemos-lhe esse direito e comprometemo-nos a respeitá-lo totalmente.
  Utilizamos cookies e informações de navegação (sessão do browser) com o objetivo de traçar o perfil do
  público que visita o site, a fim de aperfeiçoar sempre os nossos serviços, produtos e conteúdos garantindo,
  assim, as melhores ofertas e promoções aos clientes.
  Durante todo o processo, mantemos as informações pessoais em sigilo absoluto.
  </div>
     <div class="row">
		<div class="footer-redesocial col-md-12 col-lg-12">

            <div class="rede_facebook col-sm-4 col-md-4 col-lg-4">
                <center>
                    <h3>Facebook</h3>
			       <div class="fb-page" data-href="https://www.facebook.com/cantinhodasessenciassorocaba/" data-tabs="timeline" data-width="350" data-height="250" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/cantinhodasessenciassorocaba/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/cantinhodasessenciassorocaba/">Cantinho das Essências</a></blockquote></div>
                </center>
		    </div>

            <div class="rede_instragram col-sm-4 col-md-4 col-lg-4">
                <center>
                    <h3>Instagram</h3>
			        <a href="https://www.instagram.com/cantinhodasessencias/"><img class="thumb instragram" src="http://www.cantinhodasessencias.com.br/loja/pub/media/wysiwyg/thumb_instagram.png" target="_blank" rel="noopener" rel="noopener noreferrer" alt="">
                </center>
		    </div>

            <div class="rede_youtube col-sm-4 col-md-4 col-lg-4">
                <center>
                    <h3>Youtube</h3>
			        <a href="https://www.youtube.com/channel/UCLiU-oH8qm4c8gJI4rFw6jQ"><img class="thumb youtube" src="http://www.cantinhodasessencias.com.br/loja/pub/media/wysiwyg/thumb_youtube.png" target="_blank" rel="noopener" rel="noopener noreferrer" alt="" ></a>
                </center>
		    </div>

		</div>

	</div>

	<div class="footer-top">

		<div class="container-inner">

			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top')->toHtml();?>

        </div>

        <div class="footertop-col1 col-md-2 col-xs-12 col-sm-2 col-lg-2">
            <div class="footer-institucional">
		        <h3 class="footer-h3">Institucional</h3>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/index.php">Home</a></p><br>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/sobre-nos">Sobre nós</a></p><br>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/#">Produtos</a></p><br>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/cursos">Cursos</a></p><br>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/blog">Blog</a></p><br>

                    <p><a href="http://www.cantinhodasessencias.com.br/loja/contato">Contato</a></p>

            </div>
		</div>

		<div class="footertop-col2 col-md-4 col-xs-12 col-sm-4 col-lg-4">
            <div class="footer-funcionamento">
		        <h3 class="footer-h3">Horário de Funcionamento:</h3>

                <p>De segunda à sexta das 09h às 18h</p><br>

                <p>Aos sábados das 09h às 13h</p>
            </div>
            <div class="footer-trabalheconosco">
                <h3 class="footer-h3">Trabalhe conosco</h3>

                <p>Procurando emprego? Envie-nos seu currículo</p><br>

                <p>trabalhe@cantinhodasessencias.com.br</p>
            </div>
        </div>

		<div class="footertop-col3 col-md-3 col-xs-12 col-sm-3 col-lg-3">
            <div class="footer-frete">
			    <h3 class="footer-h3">Frete</h3>

                <p>Envio para todo o Brasil via PAC</p><br>

                <p>Sedex e Transportadora</p>
            </div>
            <div class="footer-formaspag">

                <h3 class="footer-h3">Formas de pagamento</h3>

                 <img src="http://cantinhodasessencias.com.br/formaspag.png" alt="" >

            </div>

		</div>

       <div class="footertop-col4 col-md-3 col-xs-12 col-sm-3 col-lg-3">
            <div class="footer-compras">
			    <h3 class="footer-h3">Compras</h3>

                <a href='http://www.cantinhodasessencias.com.br/loja/customer/account/'><p>Meus pedidos</p></a><br>

                <a href='http://www.cantinhodasessencias.com.br/loja/checkout/cart/'><p>Carrinho</p></a><br>

                <a href='http://www.cantinhodasessencias.com.br/loja/customer/account/'><p>Login</p></a>
            </div>
            <div class="footer-infoentrega">
                <h3 class="footer-h3">Informações de entrega</h3>

                <a value="infoentrega" onclick='on(1)'>Informações de entrega</a><br>

                <a value="segurancaprivacidade" onclick='on(2)'>Políticas e Privacidade</a><br>

                <a value="termoscondicoes" onclick='on(3)'>Termos & Condições</a><br>

                <a value="perguntasfrequentes" onclick='on(4)'>Perguntas Frequentes</a>
            </div>
		</div>

	</div>

	<div class="footer-bottom col-md-12 col-lg-12">

		<div class="container-inner col-md-10 col-lg-10">

			<div class="row">

				<div class="footerbottom-col1 col-md-4 col-sm-4 col-lg-4">

					<?php echo $this->getChildHtml('copyright')?>

                    <img src="http://cantinhodasessencias.com.br/logocantinho.png" alt="" style="width: 100%;">

				</div>



				<div class="footerbottom-col2 col-xs-12 col-sm-4 col-lg-4">

					<?php echo $this->getChildHtml("store_switcher"); ?>

                <p style="color:white;">R. Dr. Álvaro Soares, 380 (45.39 km) | 18010-191 Sorocaba<br><b>15 3388-6756 / 3233-8723</b></p>

				</div>

				<div class="footerbottom-col3 col-md-4 col-sm-4 col-lg-4">

					<div class="footer_payment" style="width:250px;margin-right: 25%">

						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_payment')->toHtml();?>

                             <img src="http://cantinhodasessencias.com.br/selo-ebit-site-protegido.png" class="img-fluid" alt="" style="width: 100%;">


					</div>

				</div>

			</div>

		</div>

		<div id="back_top" class="col-md-2 col-sm-2 col-lg-2">

			<a href="#back-top"><span>>top</span></a>

		</div>

	</div>
<div class="footerbottom-mobile" id="footerbottom-mobile">

					<?php echo $this->getChildHtml("store_switcher"); ?>

                <p class="midle-footer">R. Dr. Álvaro Soares, 380 (45.39 km) | 18010-191 Sorocaba<br><b>15 3388-6756 / 32338723</b></p>

				</div>
</div>



</div>
<script type="text/javascript">



	require(["jquery"], function($){



	   $(window).scroll(function() {

			if($(this).scrollTop() > 300) {

				$('#back_top').fadeIn();

			} else {

				$('#back_top').fadeOut();

			}

		});

		   $('#back_top').click(function() {

			$('body,html').animate({scrollTop:0},500);

		});



	});

</script>
<script type="text/javascript">
    var screen = screen.width;

    if(screen <= 768) document.getElementById("footerbottom-mobile").style.display = "inline-block";
    else document.getElementById("footerbottom-mobile").style.display = "none";

</script>
<script type="text/javascript">
  function off(num) {
		var classe;
		if(num == 1) classe = 'infoentrega';
		if(num == 2) classe = 'segurancaprivacidade';
		if(num == 3) classe = 'termoscondicoes';
		if(num == 4) classe = 'perguntasfrequentes';
    // document.getElementById(classe).style.display = 'none';

		// document.getElementById("maincontent").classList.remove("blurcss");
		// document.getElementsByClassName("content-home")[0].classList.remove("blurcss");
		// document.getElementsByClassName("footer")[0].classList.remove("blurcss");
  }
  function on(num) {
		var classe;
		if(num == 1) classe = 'infoentrega';
		if(num == 2) classe = 'segurancaprivacidade';
		if(num == 3) classe = 'termoscondicoes';
		if(num == 4) classe = 'perguntasfrequentes';

    // document.getElementById(classe).style.display = 'block';
		// document.getElementById("maincontent").setAttribute("class","blurcss");
		// document.getElementsByClassName("content-home")[0].setAttribute("class", "blurcss");
		// document.getElementsByClassName("footer")[0].setAttribute("class", "blurcss");

  }

</script>
