<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */

if($this->getConfig('enable_frontend')):
$testimonials = $this->getTestimonial();
?>

	<?php
	$auto = $this->getConfig('auto');
	if($auto)
		$auto = 'true';
	else
		$auto = 'false';
	$qty = $this->getConfig('qty');
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$rows = 1;
	$show_description = $this->getConfig('show_description');
	$show_next_back = $this->getConfig('show_next_back');
	$pagination = $this->getConfig('pagination');
	$speed = $this->getConfig('speed');
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = 'true';
	// if($show_navigation_control)
		// $show_navigation_control = 'true';
	// else
		// $show_navigation_control = 'false';
	?>
<div class="testimo-slider">

<div class="pt-testimonial-container">
    <?php $i = 0; ?>
	<ul class="thumb col-lg-pull col-md-pull">
		<?php foreach ($testimonials as $testimonial): ?>
			<?php $url_image = $this->getMediaFolder().$testimonial['avatar']; ?>
			<li class="pt-testimonial testithumb<?php echo $i.' ';if($i == 0) echo 'active'; $i++; ?>">
				<img class="img-circle" style="width:100%;height:100%;" alt="<?php echo $testimonial['name'] ?>" src="<?php echo $url_image; ?>"/>

			</li>

		<?php endforeach; ?>
	</ul>
	<?php $i = 0; ?>
	<div class="owl-container">
	   <ul class="ptowl">
		<?php foreach ($testimonials as $testimonial): ?>
			<?php $url_image = $this->getMediaFolder().$testimonial['avatar']; ?>

			<?php if($i < $qty): ?>
				<?php if($i%$rows == 0): ?>
					<li>
				<?php endif; ?>
					<div class="pt-testimonial">

						<div style="max-width:650px;padding-top:inherit;" class="des">
                            <img style="position:relative;top:-3.517px;left:-1vw;" class="start-bg" src="http://www.cantinhodasessencias.com.br/loja/pub/media/wysiwyg/abre_aspas.png">
                            <a href="<?php echo $this->getUrl('testimonial'); ?>"><?php if($testimonial['testimonial'] && $show_description) echo __($testimonial['testimonial']); ?></a>
                        </div>

						<!-- <div class="email"><?php echo $testimonial['email']; ?></div> -->
						<div style="height:3vw;" class="info">
							<a href="<?php echo $this->getUrl('testimonial'); ?>" class="name">
								<?php echo $testimonial['name']; ?>,
								<span class="job"><?php echo $testimonial['job']; ?></span><img style="position:relative;right:-18vw;bottom:-0.8vw;" class="end-bg" src="http://www.cantinhodasessencias.com.br/loja/pub/media/wysiwyg/fecha_aspas.png">
							</a>

						</div>
					</div>
				<?php if($i%$rows == ($rows - 1)): ?>
					</li>
				<?php endif; ?>
			<?php endif; ?>
			<?php $i++; ?>
		<?php endforeach; ?>
			<?php if($i%$rows != $rows): ?>

			<?php endif; ?>
		</ul>
	</div>


</div>
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
		$(document).ready(function(){
			$(".pt-testimonial-container .ptowl").owlCarousel({
				<?php
					if(($auto== 'true') && $speed):
				?>
				autoPlay : <?php echo $speed; ?>,
				<?php
					endif;
				?>
				items : <?php echo $default; ?>,
				itemsDesktop : [1199,<?php echo $desktop; ?>],
				itemsDesktopSmall : [980,<?php echo $desktop_small; ?>],
				itemsTablet: [768,<?php echo $tablet; ?>],
				itemsMobile : [479,<?php echo $mobile; ?>],
				slideSpeed : <?php echo $pagination; ?>,
				paginationSpeed : <?php echo $pagination; ?>,
				rewindSpeed : <?php echo $pagination; ?>,
				addClassActive: true,
				navigation : <?php echo $show_next_back; ?>,
				stopOnHover : true,
				pagination : <?php echo $show_navigation_control; ?>,
				scrollPerPage:true,
				afterMove: function(){
					x = $( ".pt-testimonial-container .owl-pagination .owl-page" ).index( $( ".pt-testimonial-container .owl-pagination .active" ));
					var testithumb = ".testithumb"+x;
					$(".pt-testimonial-container .thumb li").removeClass('active');
					$(testithumb).addClass('active');
				}
			});

			var owlslider = $(".pt-testimonial-container .ptowl").data('owlCarousel');

			function testislider(x)
			{
				owlslider.goTo(x)
			}

			$('.thumb .pt-testimonial').click(function(){
				testislider($( ".thumb .pt-testimonial" ).index( this ));
			});
		});
	});
</script>
<?php endif; ?>
